server:
  port: 8888
spring:
  application:
    name: course-service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: course-service-vod
          uri: lb://course-service-vod
          predicates:
            - Path=/*/vod/**
        - id: course-service-order
          uri: lb://course-service-order
          predicates:
            - Path=/*/order/**